name: deepfake-detectors
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.13

  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - tqdm

  - pip
  - pip:
      - einops==0.8.1
      - open_clip_torch==3.2.0
      - timm==1.0.22
