name: deepfake-detectors
channels:
  - pytorch
  - defaults

dependencies:
  - python=3.13

  - pytorch
  - torchvision
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - tqdm
  - numpy
  - pywavelets
  - pillow

  - pip
  - pip:
      - einops==0.8.1
      - open_clip_torch==3.2.0
      - timm==1.0.22
