global:
  dataset_path: <PATH_TO_DATASET>
  device_override: cuda:0  # null for auto-selection
  min_vram: 16000
  # Use the demo split when running with --demo
  split_file: ./split_demo.json
  num_threads: 8
  dry_run: false
  only_list: false

detector_args:
  - "--arch"
  - "opencliplinearnext_clipL14commonpool"
  - "--norm_type"
  - "clip"
  - "--resize_size"
  - "200"
  - "--resize_ratio"
  - "1"
  - "--resize_prob"
  - "0.2"
  - "--cmp_qual"
  - "65,100"
  - "--cmp_prob"
  - "0.5"
  - "--resizeSize"
  - "224"

training:
  - data: gan2:pre&sdXL:pre&realFFHQ:pre&realFORLAB:pre

testing:
  # Narrow testing to just the desired scenario(s).
  # Examples: "realFFHQ:fb" (Facebook real FFHQ), "gan2:fb" (Facebook StyleGAN2).
  - gan1:fb
  - realFFHQ:fb


