global:
  dataset_path: <PATH_TO_DATASET> 
  device_override: cuda:0  # null for auto-selection
  min_vram: 16000
  split_file: ./split_demo.json

  num_threads: 8
  dry_run: false
  only_list: false


detector_args:
  - "--arch"
  - "nodown"
  - "--prototype"
  - "--freeze"

training:
  - data: gan2:pre&sdXL:pre&realFFHQ:pre&realFORLAB:pre

testing:
  - gan1:fb
  - realFFHQ:fb